### ISSUE TITLE
Constant Bitrate not working

### ISSUE THREAD

**Issue by lennerd6** [Xaymar/OBS-AMD-Advanced-Media-Framework#148]
Hi,

I'm using an r9 290 TriX Sapphire edition and everything works perfectly except the bitrate. I stream csgo to twitch and i set my constant bitrate to 3400. But OBS shows that my bitrate goes from 2000-3900. This is also noticeable on stream as im moving in a quick pace. Any tips?

**Comment by lennerd6** [comment]
This happens by the way with every single version i have tried.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
first pls fix your post to fit guidelines

second set you minQP to 0 or 1

**Comment by Xaymar** [comment]
@Benman2785 The MinQP 0/1 thing is not a bug that has been reproduced yet. While I appreciate you trying to help, it's not a bug with MinQP "not working".

**Comment by lennerd6** [comment]
Well i kinda fixed it by reducing the vbv strictness from 100 to 90 and i also set minQP to 1. Thanks for the help! It still fluctuates from 3500-3700 but it will do. I reproduced the issue when i reset the minQP to 0 and VBV strictness to 100. I'm sorry for not following the guidelines.

**Comment by Xaymar** [comment]
You should never set VBV Strictness to 100%, the default for it is actually 0%. You should only ever increase the strictness if you run into problems such as massive peaks - and even then the correct solution is to enable Frame Skipping.

**Comment by lennerd6** [comment]
Okay thanks for the info. So i should set it to 0? The description of the option was a little bit misleading.

**Comment by Xaymar** [comment]
Yes, you should set it to 0.

**Comment by lennerd6** [comment]
Is there any way to reset everything to default? It would help me alot.

**Comment by Xaymar** [comment]
Presets: Reset to Default

**Comment by lennerd6** [comment]
I swear i tried to look for it for over 10 minutes :). Thanks. Also note when i reset to default it makes the VBV strictness 100.

**Comment by Xaymar** [comment]
That's odd, it should set it to 0. That's what I have set it to at least. Edit: It sets the Fullness to 100 in code, but strictness should be at 0.

**Comment by Xaymar** [comment]
I take it this issue is resolved? I have not heard anything from you for 6 days now.

**Comment by lennerd6** [comment]
Unfortunately not. Alot of the times it will go completely broken and spike 800-14000 bitrate and then i would have to change the vbv strictness like by 1% click apply and it will fix itself again. If i put it on 0% it will completely break so i put it on 80% and it seems to work but still not really. I noticed it did this after i alt-tabbed a few times or when i restarted my game. Also another issue with my stream is every 1 second if you look very closely there is some kind of mini bitrate drop like a spike but it happens every single second and its annoying. OBS doesnt really show this bitrate drop but u can notice it on stream. It happens exactly after a second and then after another second it does it again and so on. I normally am not the guy that reports bugs because i'm not good at this technical stuff but i love that this plugin doesnt give me fps drops and want it to work properly.

**Comment by Xaymar** [comment]
Well, I'd need a log file to tell that anything is wrong, which hasn't been provided yet.

Edit: Make sure to edit this issue to follow the troubleshooting guide.

**Comment by aliez3331** [comment]
sorry but where can I find some livestream settings? :/

**Comment by Xaymar** [comment]
15 days have passed, enough time to provide what the Troubleshooting Guide asked of you. I'll close this one now.
